# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: majorsilvio
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: alexa
# "service" is the name of this project. This will also be added to your AWS resource names.
service: alexa-ygo

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1

functions:
  handler:
    handler: main.handler
    events:
      - alexaSkill
